-- Player Table
CREATE TABLE dbo_player (
    PlayerID VARCHAR(20),
    PlayerFirstName VARCHAR(30),
    PlayerLastName VARCHAR(30),
    PlayerFullName VARCHAR(60),
    JerseyNumber INTEGER,
    Status VARCHAR(5) NOT NULL,
    Team VARCHAR(5),
    Position VARCHAR(5),
    NgsPosition VARCHAR(20),
    DepthChartPosition VARCHAR(5),
    Age INTEGER,
    YearsExp INTEGER,
    BirthDate TIMESTAMP,
    Height INTEGER,
    Weight INTEGER,
    College VARCHAR(50),
    DraftNumber INTEGER,
    DraftClub VARCHAR(5),
    EntryYear INTEGER,
    RookieYear INTEGER,
    HeadshotURL VARCHAR(200),
    EspnID VARCHAR(20),
    SportradarID VARCHAR(100),
    YahooID VARCHAR(20),
    RotowireID VARCHAR(20),
    PffID VARCHAR(20),
    PfrID VARCHAR(20),
    FantasyDataID VARCHAR(20),
    SleeperID VARCHAR(20),
    EsbID VARCHAR(20),
    GsisItID VARCHAR(20),
    SmartID VARCHAR(100),
    FootballName VARCHAR(30),
    StatusDescriptionAbbr VARCHAR(5),
    Season INTEGER,
    Week INTEGER,
    GameType VARCHAR(5)
);

-- Game Table
CREATE TABLE dbo_game (
    GameID VARCHAR(20) PRIMARY KEY,
    Season INTEGER NOT NULL,
    Week INTEGER NOT NULL,
    StadiumID VARCHAR(10),
    GameType VARCHAR(5),
    GameDay DATE,
    WeekDay VARCHAR(10),
    GameTime TIME,
    Location VARCHAR(10),
    AwayTeam VARCHAR(5) NOT NULL,
    HomeTeam VARCHAR(5) NOT NULL,
    DivGame BOOLEAN,
    AwayScore FLOAT,
    HomeScore FLOAT,
    Total FLOAT,
    Overtime BOOLEAN,
    Result FLOAT,
    AwayRest INTEGER,
    HomeRest INTEGER,
    Temp INTEGER,
    Wind INTEGER,
    AwayMoneyline FLOAT,
    HomeMoneyline FLOAT,
    SpreadLine FLOAT,
    HomeSpreadOdds FLOAT,
    AwaySpreadOdds FLOAT,
    TotalLine FLOAT,
    UnderOdds FLOAT,
    OverOdds FLOAT
);

-- Injury Table
CREATE TABLE dbo_injury (
    Season INTEGER,
    Week INTEGER,
    GsisID VARCHAR(20),
    FirstName VARCHAR(30),
    LastName VARCHAR(30),
    FullName VARCHAR(30),
    GameType VARCHAR(5),
    Team VARCHAR(5) NOT NULL,
    Position VARCHAR(5) NOT NULL,
    ReportPrimaryInjury VARCHAR(100),
    ReportSecondaryInjury VARCHAR(100),
    ReportStatus VARCHAR(25),
    PracticePrimaryInjury VARCHAR(100),
    PracticeSecondaryInjury VARCHAR(100),
    PracticeStatus VARCHAR(100),
    DateModified TIMESTAMP,
    PRIMARY KEY (Season, Week, GsisID)
);

-- Stadium Table
CREATE TABLE dbo_stadium (
    StadiumID VARCHAR(10) PRIMARY KEY,
    StadiumName VARCHAR(100) NOT NULL,
    Roof VARCHAR(20),
    Surface VARCHAR(20)
);

-- Props Table
CREATE TABLE dbo_playerprops (
    PlayerName VARCHAR(60) NOT NULL,
    EventID VARCHAR(50) NOT NULL,
    CommenceTime TIMESTAMP,
    AwayTeam VARCHAR(50) NOT NULL,
    HomeTeam VARCHAR(50) NOT NULL,
    BookmakerKey VARCHAR(50),
    BookmakerTitle VARCHAR(50),
    MarketKey VARCHAR(100),
    OutcomeName VARCHAR(10),
    Price FLOAT,
    Point FLOAT,
    RefreshTime TIMESTAMP
);

-- Play By Play Table
CREATE TABLE dbo_playbyplay (
    GameID VARCHAR(20),
    PlayID INTEGER,
    QTR INTEGER NOT NULL,
    Drive INTEGER NOT NULL,
    Down INTEGER,
    Shotgun BOOLEAN,
    NoHuddle BOOLEAN,
    QbDropback BOOLEAN,
    QbScramble BOOLEAN,
    CompletePass BOOLEAN,
    IncompletePass BOOLEAN,
    PassingYards NUMERIC(10,1),
    AirYards NUMERIC(10,1),
    YardsAfterCatch NUMERIC(10,1),
    FirstDownPass BOOLEAN,
    PassingTouchdown BOOLEAN,
    ReceivingYards NUMERIC(10,1),
    Interception BOOLEAN,
    Fumble BOOLEAN,
    Sack BOOLEAN,
    RushAttempt BOOLEAN,
    RushingYards NUMERIC(10,1),
    RushingTouchdown BOOLEAN,
    FirstDownRush BOOLEAN,
    FieldGoalAttempt BOOLEAN,
    ExtraPointAttempt BOOLEAN,
    PuntAttempt BOOLEAN,
    KickoffAttempt BOOLEAN,
    FieldGoalResult VARCHAR(10),
    ExtraPointResult VARCHAR(10),
    Safety BOOLEAN,
    Penalty BOOLEAN,
    Season INTEGER,
    Week INTEGER,
    PasserPlayerID VARCHAR(20),
    ReceiverPlayerID VARCHAR(20),
    RusherPlayerID VARCHAR(20),
    KickerPlayerID VARCHAR(20),
    StadiumID VARCHAR(10),
    PRIMARY KEY (GameID, PlayID)
);
